language: objective-c
osx_image: xcode7.1

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=BitcoinFinder.xcworkspace
  - IOS_FRAMEWORK_SCHEME="BitcoinFinder"

  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="iphonesimulator8.1"     RUN_TESTS="YES" POD_LINT="YES"
    - DESTINATION="OS=8.2,name=iPhone 5"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="iphonesimulator8.2"     RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=8.3,name=iPhone 5S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="iphonesimulator8.3"     RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=8.4,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="iphonesimulator8.4"     RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="iphonesimulator9.0"     RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=9.1,name=iPhone 6S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="iphonesimulator9.1"     RUN_TESTS="YES" POD_LINT="NO"

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

cache:
  - bundler
  - cocoapods

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild build test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c