language: objective-c
osx_image: xcode7.1

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=BitcoinFinder.xcworkspace
  - IOS_FRAMEWORK_SCHEME="BitcoinFinder"
  - SDK="iphonesimulator9.1"
  - CODE_COVERAGE=YES


  matrix:
    - DESTINATION="OS=9.1,name=iPhone 4S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$SDK"
    - DESTINATION="OS=9.1,name=iPhone 5"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$SDK"
    - DESTINATION="OS=9.1,name=iPhone 5S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$SDK"
    - DESTINATION="OS=9.1,name=iPhone 6"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$SDK"
    - DESTINATION="OS=9.1,name=iPhone 6 Plus"      SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$SDK"
    - DESTINATION="OS=9.1,name=iPhone 6S"          SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$SDK"

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

cache:
  - bundler
  - cocoapods

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild build test -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -enableCodeCoverage $CODE_COVERAGE -GCC_GENERATE_TEST_COVERAGE_FILES=YES -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)