language: objective-c
osx_image: xcode7.2

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

cache:
  - bundler
  - cocoapods

script:
  - xcodebuild -workspace BitcoinFinder.xcworkspace -scheme 'BitcoinFinderTests' -sdk iphonesimulator clean build | xcpretty -c > build.log
  - xcodebuild -workspace BitcoinFinder.xcworkspace -scheme 'BitcoinFinderTests' -sdk iphonesimulator -enableCodeCoverage YES test | xcpretty -c > build.log && exit ${PIPESTATUS[0]}

after_failure:
  - tail -n 500 build.log

after_success:
  - bash <(curl -s https://codecov.io/bash)