language: objective-c
osx_image: xcode7.2
cache: cocoapods

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document
  - gem install xcpretty --no-rdoc --no-ri --no-document

script:
  - xcodebuild test -workspace BitcoinFinder.xcworkspace -scheme BitcoinFinderTests -destination 'platform=iOS Simulator,OS=9.2,name=iPhone 6s' -sdk iphonesimulator -enableCodeCoverage YES | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)