language: objective-c
osx_image: xcode7.2

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

cache:
  - bundler
  - cocoapods

script:
  - open -b com.apple.iphonesimulator
  - xcodebuild test -workspace BitcoinFinder.xcworkspace -scheme BitcoinFinderTests -destination 'platform=iOS Simulator,OS=9.2,name=iPhone 6s' -sdk iphonesimulator -enableCodeCoverage YES | xcpretty -c > build.log && exit ${PIPESTATUS[0]}

after_failure:
  - tail -n 500 build.log

after_success:
  - bash <(curl -s https://codecov.io/bash)